  version: '3.4'
  services:
    db:
      image: mysql
      container_name: mysql
      ports:
        - "3306:3306"
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root

    web:
      image: tomcat:latest
      container_name: tomcat
      ports:
        - "8080:8080"
      volumes:
        - ./target:/usr/local/tomcat/webapps
      links:
        - db
